### ISSUE TITLE
oneflow_onnx.oneflow2onnx.util import export_onnx_model模块导入问题

### ISSUE THREAD

**Issue by process852** [Oneflow-Inc/oneflow_convert#107]
oneflow_onnx.oneflow2onnx.util import export_onnx_model模块导入报错？
* 更新[文档](https://docs.oneflow.org/master/cookies/oneflow2onnnx.html)中遇到的问题
* 文档中给出的测试代码如下:
```python
from oneflow_onnx.oneflow2onnx.util import export_onnx_model

export_onnx_model(graph,
                  external_data=False, 
                  opset=None, 
                  flow_weight_dir=None, 
                  onnx_model_path="/tmp", 
                  dynamic_batch_size=False)
```
* 报错信息如下：
![image](https://user-images.githubusercontent.com/62278179/205856081-ea614762-01da-46c0-80bb-fe0451dc4e60.png)
* 目前做了以下两个方面的排查
 1. 检查运行python程序时是否包含该包的路径，发现路径已经包含在`sys.path`中
![image](https://user-images.githubusercontent.com/62278179/205856747-80df1825-7a2a-4aa5-bf63-178a751ea0af.png)
 2. 检查`oneflow_onnx`是否缺少`__init__.py`文件
![image](https://user-images.githubusercontent.com/62278179/205857873-ca04635a-fe48-4aab-901c-9b614e930d7f.png)
但仍未解决相关问题
* 相关包的版本信息如下：
```
python    3.8
oneflow            0.8.1.dev20221201+cu112
oneflow-onnx       0.6.1
onnx               1.12.0
onnx-simplifier    0.4.10
onnxoptimizer      0.3.2
onnxruntime-gpu    1.13.1
```

**Comment by BBuf** [comment]
是什么时候安装的呢？

**Comment by BBuf** [comment]
可以卸载重装一下试试，我刚才重新试了一下 pip install oneflow_onnx 是正常的

**Comment by process852** [comment]
今天刚装的，我试试

**Comment by BBuf** [comment]
> 我重新试了一下，还是会报错，你这边可以截个图看一下相关依赖包的版本吗，不知道是不是相关版本高低也会有影响

![图片](https://user-images.githubusercontent.com/35585791/205868220-dcd53567-a1ec-4198-8822-0d58cf1e5d40.png)

**Comment by BBuf** [comment]
![图片](https://user-images.githubusercontent.com/35585791/205868435-55211c1f-9df9-4ba3-bcd1-922188ddb5ae.png)

**Comment by process852** [comment]
问题已解决，软件没问题。我看到目录下有个同名文件覆盖了包里的文件。
